# This workflow will build an Xcode project for iOS
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Xcode
      run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

    - name: Build
      run: xcodebuild -scheme <Twine.xcscheme_^#shared#^_> -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12' build

    - name: Run tests
      run: xcodebuild -scheme <Twine.xcscheme_^#shared#^_> -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12' test
